const data = [
  {
    _id: '1',
    name: 'Social Media App',
    imgUrl: 'bg-pj4',
    content: 'Based on Facebook',
    tech: ['VueJs', 'Django', 'TailwindCSS', 'Pinia', 'Vite', 'pusher-js'],
    url: 'https://social-network-2024.vercel.app/',
    code: 'https://github.com/Void168/Social-network',
    description:
      "This app is created during the learning process VueJS and Django based on a small part of Facebook. The front-end is used VueJS and it is hosted on Vercel. The back-end is used Django it is hosted on pythonanywhere.com. Feed just display order by day (I'm not qualified enough to display Facebook's algorithm). The site is not displayed on ios device because of Object.groupBy() method, which is being in experiment on ios 17.4", 
    features: [
      'Login/Sign Up (avtivate by gmail)',
      'Search Engine (search user, post, page, keywords)',
      'User (add friends, set relationship, follow/unfollow, information)',
      'Feed (trends, posts, page posts, infinite scroll)',
      'Post (comment, tag, like, avatar post, crud)',
      'Notification (like, tag, add friend, set relationship, comment)',
      'Real-time chat (user-user, group (with group setting), user-page, theme, group poll, emotion, media file, crud conversation)',
      'Page (follow/unfollow, page type, admin, moderators, crud)',
      'Group ( discover groups, join public group, request join group, pending posts, group search keywords, admin, moderators, group poll, dashboard, rules, questions to join group, crud)',
      'Story ( create text/media story, react emotion, crud, list seen users)',
      'Responsive on all device (except ios)'
    ],
  },
  {
    _id: '2',
    name: 'Chat App',
    imgUrl: 'bg-pj5',
    content: 'Chat real-time online',
    tech: ['Next.js', 'Tailwind CSS', 'Prisma', 'MongoDB', 'Zustand', 'pusher-js'],
    url: 'https://message-send-app.vercel.app/',
    code: 'https://github.com/Void168/Chatapp',
    description: 'This is the practice project about Typescript and NextJS 13. The website can help people connect with each other by send messages.',
    features: [
      'Authentication with google/github',
      'Single conversation',
      'Group conversation',
      'Real-time chat',
      'Update user profile',
    ],
  },
  {
    _id: '3',
    name: 'Booking App',
    imgUrl: 'bg-pj6',
    content: 'Practice NextJS and Typescript',
    tech: ['Next.js', 'Typescript', 'Tailwind CSS', 'Prisma', 'MongoDB', 'Zustand'],
    url: 'https://booking-brown.vercel.app/',
    code: 'https://github.com/Void168/Booking',
    description: 'This is the practice project about Typescript and NextJS 13. The website help people create their own place to tourism and tourists can book a place to serve their vacation',
    features: [
      'Sign in & Sign up by (can sign up with Google & Github)',
      'Filter by place, date, amount',
      'Booking funtion',
      'Favorite Listings',
      'Manage listings',
    ],
  },
  {
    _id: '4',
    name: 'Weirdshop',
    imgUrl: 'bg-pj1',
    content: 'Technology Sales Website',
    tech: [
      'ReactJs',
      'Tailwind CSS',
      'Redux Toolkit',
      'NodeJs',
      'ExpressJs',
      'MongoDB',
    ],
    url: 'https://weirdshop.netlify.app/',
    code: 'https://github.com/Void168/Ecommerce2',
    description:
      'This app was built using React JS for front-end; MongoDb, Express Js, Node Js for back-end and is hosted on Render.com. I had build a completely customized eCommerce application with the MERN stack with the following functionality',
    features: [
      'Login/Sign Up',
      'Product Pagination',
      'Search Engine',
      'Product Sort/Filter',
      'Best Seller',
      'Viewed Products',
      'User orders',
      'User Profile',
      'Admin products/users/orders management',
      'Admin chart',
      'Details order',
      'Shopping Cart',
      'Checkout process (shipping, payment method, etc)',
      'Landing Page',
      'Review/Rating Product',
    ],
  },
  {
    _id: '5',
    name: 'Spotify Clone',
    imgUrl: 'bg-pj3',
    content: 'Clone music website based on spotify',
    tech: [
      'ReactJs',
      'Vite',
      'Tailwind CSS',
      'Redux Toolkit',
      'Rapid Api (Shazam)',
    ],
    url: 'https://musizfy.netlify.app/',
    code: 'https://github.com/Void168/Spotify_clone',
    description:
      'This app was built based on Spotify using ReactJS and Tailwind CSS for front-end. All songs are get by using Rapid API of javascript mastery',
    features: [
      'Search engine',
      'Play/Pause/Next/Prev song',
      'Filter your country songs',
      'Top Charts',
      'Top Artists',
    ],
  },
  {
    _id: '6',
    name: 'Restaurant UI',
    imgUrl: 'bg-pj2',
    content: 'Build UI Landing Website',
    tech: ['ReactJs', 'CSS3'],
    url: 'https://chefhoangdung.netlify.app/',
    code: 'https://github.com/Void168/Restaurant-UI',
    description:
      'This landing page was built using React JS and CSS with all responsive devices',
    features: ['Build the static UX/UI landing page'],
  },
]

export default data
