const data = [
  {
    _id: '1',
    name: 'Weirdshop',
    imgUrl: 'bg-pj1',
    content: 'Technology Sales Website',
    tech: [
      'ReactJs',
      'Tailwind CSS',
      'Redux Toolkit',
      'NodeJs',
      'ExpressJs',
      'MongoDB',
    ],
    url: 'https://weirdshop.netlify.app/',
    code: 'https://github.com/Void168/Ecommerce2',
    description:
      'This app was built using React JS for front-end; MongoDb, Express Js, Node Js for back-end and is hosted on Render.com. I had build a completely customized eCommerce application with the MERN stack with the following functionality',
    features: [
      'Login/Sign Up',
      'Product Pagination',
      'Search Engine',
      'Product Sort/Filter',
      'Best Seller',
      'Viewed Products',
      'User orders',
      'User Profile',
      'Admin products/users/orders management',
      'Admin chart',
      'Details order',
      'Shopping Cart',
      'Checkout process (shipping, payment method, etc)',
      'Landing Page',
      'Review/Rating Product',
    ],
  },
  {
    _id: '2',
    name: 'Restaurant UI',
    imgUrl: 'bg-pj2',
    content: 'Build UI Landing Website',
    tech: ['ReactJs', 'CSS3'],
    url: 'https://chefhoangdung.netlify.com/',
    code: 'https://github.com/Void168/Restaurant-UI',
    description:
      'This landing page was built using React JS and CSS with all responsive devices',
    features: ['Build the static UX/UI landing page'],
  },
  {
    _id: '3',
    name: 'Spotify Clone',
    imgUrl: 'bg-pj3',
    content: 'Clone music website based on spotify',
    tech: [
      'ReactJs',
      'Vite',
      'Tailwind CSS',
      'Redux Toolkit',
      'Rapid Api (Shazam)',
    ],
    url: 'https://musizfy.netlify.app/',
    code: 'https://github.com/Void168/Spotify_clone',
    description:
      'This app was built based on Spotify using ReactJS and Tailwind CSS for front-end. All songs are get by using Rapid API of javascript mastery',
    features: [
      'Search engine',
      'Play/Pause/Next/Prev song',
      'Filter your country songs',
      'Top Charts',
      'Top Artists',
    ],
  },
  {
    _id: '4',
    name: 'Hfood',
    imgUrl: 'bg-pj4',
    content: 'Food Sales Website',
    tech: ['ReactJs', 'MUI', 'CSS', 'Redux', 'NodeJs', 'ExpressJs', 'MongoDB'],
    url: 'blank',
    code: 'https://github.com/Void168/Hfood-reup',
    description:
      'This is my graduation thesis but not deploy on site yet. This app was built using React JS for front-end; MongoDb, Express Js, Node Js for back-end and is hosted on Render.com .I had build a completely customized eCommerce application with the MERN stack with the following functionality',
    features: [
      'Login/Sign Up',
      'Search Engine',
      'Product Sort/Filter',
      'Viewed Products',
      'User orders',
      'User Profile',
      'Admin products/users/orders management',
      'Details order',
      'Shopping Cart',
      'Checkout process (shipping, payment method, etc)',
      'Review/Rating Product',
    ],
  },
  {
    _id: '5',
    name: 'FoodApp Mobile',
    imgUrl: 'bg-pj5',
    content: 'Practice React Native by building food order app',
    tech: ['React Native', 'Tailwind CSS', 'Redux Toolkit', 'Sanity.io'],
    url: 'blank',
    code: 'https://github.com/Void168/FoodApp',
    description: 'This is the practice project about react native',
    features: [
      'Home page',
      'Restaurant details',
      'List categories/foods',
      'Cart',
      'Payment UI',
      'Map Position',
    ],
  },
  {
    _id: '6',
    name: 'Portfolio',
    imgUrl: 'bg-pj6',
    content: 'My Portfolio',
    tech: ['ReactJs', 'Vite', 'Tailwind CSS'],
    url: 'https://github.com/Void168/Portfolio',
    code: 'https://github.com/Void168/Portfolio',
    description: 'This is my fortfolio',
    features: [
      'Home section',
      'About section',
      'Work section',
      'Contact section',
    ],
  },
]

export default data
